//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmissionsCommittee.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdmissionsCommitteeDBContainer : DbContext
    {
        public AdmissionsCommitteeDBContainer()
            : base("name=AdmissionsCommitteeDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<University> UniversitySet { get; set; }
        public virtual DbSet<Faculty> FacultySet { get; set; }
        public virtual DbSet<Department> DepartmentSet { get; set; }
        public virtual DbSet<Flow> FlowSet { get; set; }
        public virtual DbSet<Group> GroupSet { get; set; }
        public virtual DbSet<Enrollee> EnrolleeSet { get; set; }
        public virtual DbSet<Exam_sheet> Exam_sheetSet { get; set; }
        public virtual DbSet<Exam_statement> Exam_statementSet { get; set; }
        public virtual DbSet<Subject> SubjectSet { get; set; }
        public virtual DbSet<Exam_schedule> Exam_scheduleSet { get; set; }
        public virtual DbSet<Consultation> ConsultationSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
    }
}
