//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmissionsCommittee.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_statement
    {
        public int Id { get; set; }
        public byte Mark { get; set; }
        public short Points { get; set; }
    
        public virtual Enrollee Enrollee { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
